apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: trabalho02
data:
  # POSTGRES
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "periodicos"

  # MINIO
  S3_ENDPOINT: "http://minio:9000"
  S3_BUCKET: "bucket-periodicos"

  # DYNAMODB
  AWS_REGION: "us-east-1"
  DDB_TABLE: "Logs"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: trabalho02
type: Opaque
stringData:
  # POSTGRES
  DB_USER: "admin_periodicos"
  DB_PASSWORD: "periodicos123"

  # MINIO
  S3_ACCESS_KEY: "MINIO_PLACEHOLDER"
  S3_SECRET_KEY: "MINIO_PLACEHOLDER"

  # AWS (coloque aqui as credenciais reais só no seu ambiente, não no GitHub!)
  AWS_ACCESS_KEY_ID: "REPLACE_AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "REPLACE_AWS_SECRET_ACCESS_KEY"

